default:
  outputs:
    default:
      type: materialize
      threads: 1
      host: "{{ env_var('MZ_HOST')}}"
      port: 6875
      user: "{{ env_var('MZ_USER')}}"
      pass: "{{ env_var('MZ_PASS')}}"
      database: "materialize"
      schema: "public"
      cluster: "default"
      sslmode: require

  target: default
